project_id = "qekexdtidnbspqzwerrd"

[functions.seed-admin]
verify_jwt = false

[functions.manage-users]
verify_jwt = false

[functions.send-billing-email]
verify_jwt = false

[functions.scan-invoice]
verify_jwt = false

[functions.backup-restore]
verify_jwt = false

[functions.wms-sync]
verify_jwt = false
